### ISSUE TITLE
cuda testing

### ISSUE THREAD

**Issue by wconnell** [wconnell/enformer-finetune#3]
unable to test training locally, need to test on cuda

**Comment by wconnell** [comment]
@aaronwtr can you spin up some testing on your cluster? there are prob some bugs to troubleshoot but you can launch a training run with the command `python main.py fit --config config.yaml`

you'll need to modify the `config.yaml` file which has all of the args for the lightning `Trainer`, `data` and `model`

basically after getting it running I think we can redo our experiments from the colab to look at correlations and plot some tracks. i'm out of town this weekend but just log any issues here and I will help out!

**Comment by aaronwtr** [comment]
@wconnell I'll give it a go either this weekend or early next week. I'll keep you updated!
